### ISSUE TITLE
Upload image and camera options do not work

### ISSUE THREAD

**Issue by dylanneve1** [D4rK7355608/com.google.android.apps.bard#1]
Update image and camera buttons do not seem to function at all. Have tried multiple times and closed and restarted the app to no avail. Would be very handy if this issue could be fixed as it could completely replace using the website.

**Comment by MihaiCristianCondrea** [comment]
Thanks for reporting this issue. I'm aware that the image upload and camera options are not working in the latest version of the app, and I'm working on a fix. I expect to release a new version of the app within the next week that will address this issue.

In the meantime, you can still upload images and use the camera by visiting the website on your browser.

I apologize for the inconvenience, and I appreciate your patience.
